#!/usr/bin/env python3
"""
Test Demo Hook - Generates Lorem Ipsum test.md file

This hook demonstrates the framework's hook system by generating
a simple test file with Lorem Ipsum content.

Usage:
    python3 .claude/hooks/test_demo_hook.py --output <path> [--paragraphs N] [--title "Title"]

Arguments:
    --output      Output file path (required)
    --paragraphs  Number of paragraphs to generate (default: 3)
    --title       Title for the generated file (default: "Test Demo Output")
    --source      Source identifier (command, skill, agent, subagent)

Returns:
    JSON with generation details
"""

import argparse
import json
import os
import sys
from datetime import datetime
from pathlib import Path

# Lorem Ipsum paragraphs
LOREM_PARAGRAPHS = [
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.",
    "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.",
    "Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem."
]


def generate_lorem_content(title: str, paragraphs: int, source: str) -> str:
    """Generate Lorem Ipsum markdown content."""
    timestamp = datetime.now().isoformat()

    content_lines = [
        f"# {title}",
        "",
        f"> Generated by: `{source}`",
        f"> Timestamp: {timestamp}",
        "",
        "---",
        "",
        "## Content",
        ""
    ]

    # Add requested number of paragraphs (cycling through available)
    for i in range(paragraphs):
        content_lines.append(LOREM_PARAGRAPHS[i % len(LOREM_PARAGRAPHS)])
        content_lines.append("")

    content_lines.extend([
        "---",
        "",
        "## Metadata",
        "",
        "| Property | Value |",
        "|----------|-------|",
        f"| Source | {source} |",
        f"| Paragraphs | {paragraphs} |",
        f"| Generated | {timestamp} |",
        "",
        "---",
        "",
        "*This file was generated by the HTEC Framework Test Demo to demonstrate hook functionality.*"
    ])

    return "\n".join(content_lines)


def main():
    parser = argparse.ArgumentParser(description="Generate Lorem Ipsum test file")
    parser.add_argument("--output", required=True, help="Output file path")
    parser.add_argument("--paragraphs", type=int, default=3, help="Number of paragraphs")
    parser.add_argument("--title", default="Test Demo Output", help="Document title")
    parser.add_argument("--source", default="hook", help="Source identifier")

    args = parser.parse_args()

    try:
        # Ensure output directory exists
        output_path = Path(args.output)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        # Generate content
        content = generate_lorem_content(args.title, args.paragraphs, args.source)

        # Write file
        output_path.write_text(content)

        # Return success JSON
        result = {
            "success": True,
            "output_file": str(output_path),
            "title": args.title,
            "paragraphs": args.paragraphs,
            "source": args.source,
            "timestamp": datetime.now().isoformat(),
            "file_size": len(content)
        }

        print(json.dumps(result))
        return 0

    except Exception as e:
        error_result = {
            "success": False,
            "error": str(e),
            "source": args.source
        }
        print(json.dumps(error_result), file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
